### ISSUE TITLE
Plex-mpv-shim can't find libmpv1, python virtual environment to blame?

### ISSUE THREAD

**Issue by Retrograde-i486** [iwalton3/plex-mpv-shim#115]
I've been trying to fix plex-mpv-shim for weeks now on Arch Linux. Had it working months ago but it's been broken on my system for a long time now.

I've installed it via pipx and that completes successfully:

```
$ pipx install plex-mpv-shim
⚠  Note: plex-mpv-shim was already on your PATH at /usr/bin/plex-mpv-shim
  installed package plex-mpv-shim 1.11.0, installed using Python 3.12.3
  These apps are now globally available
    - plex-mpv-shim
done! ✨ 🌟 ✨
```

But when trying to run it I get this error: 

```
plex-mpv-shim
2024-05-15 13:01:48,864 [   ERROR] conf: Error loading settings from json: Expecting value: line 41 column 21 ❯ plex-mpv-shim
2024-05-15 13:02:57,641 [   ERROR] conf: Error loading settings from json: Expecting value: line 41 column 21 (char 1089)
2024-05-15 13:02:57,641 [ WARNING] root: Cannot load GUI. Falling back to command line interface.
Traceback (most recent call last):
  File "/usr/lib/python3.12/site-packages/plex_mpv_shim/mpv_shim.py", line 39, in main
    from .gui_mgr import userInterface
  File "/usr/lib/python3.12/site-packages/plex_mpv_shim/gui_mgr.py", line 1, in <module>
    from pystray import Icon, MenuItem, Menu
ModuleNotFoundError: No module named 'pystray'
2024-05-15 13:02:57,685 [ WARNING] player: Could not find libmpv1.
Traceback (most recent call last):
  File "/usr/bin/plex-mpv-shim", line 33, in <module>
    sys.exit(load_entry_point('plex-mpv-shim==1.11.0', 'console_scripts', 'plex-mpv-shim')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/plex_mpv_shim/mpv_shim.py", line 47, in main
    from .player import playerManager
  File "/usr/lib/python3.12/site-packages/plex_mpv_shim/player.py", line 31, in <module>
    import python_mpv_jsonipc as mpv
ModuleNotFoundError: No module named 'python_mpv_jsonipc'

```
My best guess is that because it's installed in a python virtual environment that's causing it trouble loading up shared libraries but i'm no python expert so I don't know. The warnings about Cannot load GUI and pystray never bothered me since I never used them in the past when I did have plex-mpv-shim working. Any help or pointers in the right direction would be greatly appreciated!

**Comment by polyzen** [comment]
aur/plex-mpx-shim should be working now that extra/python-mpv is updated. If you have anything under /usr/lib/python3.11, that probably means you need to rebuild the corresponding AUR packages.

**Comment by Retrograde-i486** [comment]
> aur/plex-mpx-shim should be working now that extra/python-mpv is updated. If you have anything under /usr/lib/python3.11, that probably means you need to rebuild the corresponding AUR packages.

Hey, I saw your post on the AUR plex-mpv-shim, thanks for responding. I've rebuilt from the AUR before, just tried it again, installed fine but still get the same error messages. By "anything under /usr/lib/python3.11" do you mean anything related to plex-mpv-shim or just in general? Because I have a ton of stuff in there including two folders related to plex-mpv-shim (plex_mpv_shim & plex_mpv_shim-1.11.0.dist-info). Should i just delete those two folders?

**Comment by polyzen** [comment]
Those are leftovers from before we updated to Python 3.12. You should not have to manually delete them. If you installed stuff there using pip, you should be able to remove them using pip. Anything from the AUR just rebuild and install the new package.

**Comment by Retrograde-i486** [comment]
Alright I removed the two leftover folders and then pulled down the latest from the AUR, ran makepkg -sic which appeared to build correctly and then tried running plex-mpv-shim and got the same error as before. Apologies for the wall of text but here's everything I did:


git clone https://aur.archlinux.org/plex-mpv-shim.git
Cloning into 'plex-mpv-shim'...
hint: Using 'master' as the name for the initial branch. This default branch name
hint: is subject to change. To configure the initial branch name to use in all
hint: of your new repositories, which will suppress this warning, call:
hint:
hint:   git config --global init.defaultBranch <name>
hint:
hint: Names commonly chosen instead of 'master' are 'main', 'trunk' and
hint: 'development'. The just-created branch can be renamed via this command:
hint:
hint:   git branch -m <name>
remote: Enumerating objects: 52, done.
remote: Counting objects: 100% (52/52), done.
remote: Compressing objects: 100% (39/39), done.
remote: Total 52 (delta 13), reused 52 (delta 13), pack-reused 0 (from 0)
Receiving objects: 100% (52/52), 12.46 KiB | 12.46 MiB/s, done.
Resolving deltas: 100% (13/13), done.
❯ cd plex-mpv-shim
❯ ll
total 40
drwxr-xr-x 1 user user   40 May 15 15:54 ./
drwxrw---- 1 user user 2434 May 15 15:54 ../
drwxr-xr-x 1 user user  138 May 15 15:54 .git/
-rw-r--r-- 1 user user 1185 May 15 15:54 PKGBUILD
-rw-r--r-- 1 user user  742 May 15 15:54 .SRCINFO
❯ makepkg -sic
==> Making package: plex-mpv-shim 1.11.0-1 (Wed 15 May 2024 03:54:43 PM EDT)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
  -> Downloading plex-mpv-shim-1.11.0.tar.gz...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 86989    0 86989    0     0   493k      0 --:--:-- --:--:-- --:--:--  493k
==> Validating source files with b2sums...
    plex-mpv-shim-1.11.0.tar.gz ... Passed
==> Extracting sources...
  -> Extracting plex-mpv-shim-1.11.0.tar.gz with bsdtar
==> Starting build()...
running build
running build_py
creating build
creating build/lib
creating build/lib/plex_mpv_shim
copying plex_mpv_shim/__init__.py -> build/lib/plex_mpv_shim
copying plex_mpv_shim/action_thread.py -> build/lib/plex_mpv_shim
copying plex_mpv_shim/bulk_subtitle.py -> build/lib/plex_mpv_shim
copying plex_mpv_shim/cli_mgr.py -> build/lib/plex_mpv_shim
copying plex_mpv_shim/client.py -> build/lib/plex_mpv_shim
copying plex_mpv_shim/conf.py -> build/lib/plex_mpv_shim
copying plex_mpv_shim/conffile.py -> build/lib/plex_mpv_shim
copying plex_mpv_shim/gdm.py -> build/lib/plex_mpv_shim
copying plex_mpv_shim/gui_mgr.py -> build/lib/plex_mpv_shim
copying plex_mpv_shim/media.py -> build/lib/plex_mpv_shim
copying plex_mpv_shim/menu.py -> build/lib/plex_mpv_shim
copying plex_mpv_shim/mpv_shim.py -> build/lib/plex_mpv_shim
copying plex_mpv_shim/player.py -> build/lib/plex_mpv_shim
copying plex_mpv_shim/subscribers.py -> build/lib/plex_mpv_shim
copying plex_mpv_shim/svp_integration.py -> build/lib/plex_mpv_shim
copying plex_mpv_shim/timeline.py -> build/lib/plex_mpv_shim
copying plex_mpv_shim/utils.py -> build/lib/plex_mpv_shim
copying plex_mpv_shim/video_profile.py -> build/lib/plex_mpv_shim
copying plex_mpv_shim/win_utils.py -> build/lib/plex_mpv_shim
running egg_info
creating plex_mpv_shim.egg-info
writing plex_mpv_shim.egg-info/PKG-INFO
writing dependency_links to plex_mpv_shim.egg-info/dependency_links.txt
writing entry points to plex_mpv_shim.egg-info/entry_points.txt
writing requirements to plex_mpv_shim.egg-info/requires.txt
writing top-level names to plex_mpv_shim.egg-info/top_level.txt
writing manifest file 'plex_mpv_shim.egg-info/SOURCES.txt'
reading manifest file 'plex_mpv_shim.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no files found matching '*' under directory 'plex_mpv_shim/default_shader_pack'
adding license file 'LICENSE.md'
writing manifest file 'plex_mpv_shim.egg-info/SOURCES.txt'
copying plex_mpv_shim/mouse.lua -> build/lib/plex_mpv_shim
copying plex_mpv_shim/systray.png -> build/lib/plex_mpv_shim
==> Entering fakeroot environment...
==> Starting package()...
running install
/usr/lib/python3.12/site-packages/setuptools/_distutils/cmd.py:66: SetuptoolsDeprecationWarning: setup.py install is deprecated.
!!

        ********************************************************************************
        Please avoid running ``setup.py`` directly.
        Instead, use pypa/build, pypa/installer or other
        standards-based tools.

        See https://blog.ganssle.io/articles/2021/10/setup-py-deprecated.html for details.
        ********************************************************************************

!!
  self.initialize_options()
running install_lib
creating /home/user/Downloads/plex-mpv-shim/pkg/plex-mpv-shim/usr
creating /home/user/Downloads/plex-mpv-shim/pkg/plex-mpv-shim/usr/lib
creating /home/user/Downloads/plex-mpv-shim/pkg/plex-mpv-shim/usr/lib/python3.12
creating /home/user/Downloads/plex-mpv-shim/pkg/plex-mpv-shim/usr/lib/python3.12/site-packages
creating /home/user/Downloads/plex-mpv-shim/pkg/plex-mpv-shim/usr/lib/python3.12/site-packages/plex_mpv_shim
copying build/lib/plex_mpv_shim/__init__.py -> /home/user/Downloads/plex-mpv-shim/pkg/plex-mpv-shim/usr/lib/python3.12/site-packages/plex_mpv_shim
copying build/lib/plex_mpv_shim/action_thread.py -> /home/user/Downloads/plex-mpv-shim/pkg/plex-mpv-shim/usr/lib/python3.12/site-packages/plex_mpv_shim
copying build/lib/plex_mpv_shim/bulk_subtitle.py -> /home/user/Downloads/plex-mpv-shim/pkg/plex-mpv-shim/usr/lib/python3.12/site-packages/plex_mpv_shim
copying build/lib/plex_mpv_shim/cli_mgr.py -> /home/user/Downloads/plex-mpv-shim/pkg/plex-mpv-shim/usr/lib/python3.12/site-packages/plex_mpv_shim
copying build/lib/plex_mpv_shim/client.py -> /home/user/Downloads/plex-mpv-shim/pkg/plex-mpv-shim/usr/lib/python3.12/site-packages/plex_mpv_shim
copying build/lib/plex_mpv_shim/conf.py -> /home/user/Downloads/plex-mpv-shim/pkg/plex-mpv-shim/usr/lib/python3.12/site-packages/plex_mpv_shim
copying build/lib/plex_mpv_shim/conffile.py -> /home/user/Downloads/plex-mpv-shim/pkg/plex-mpv-shim/usr/lib/python3.12/site-packages/plex_mpv_shim
copying build/lib/plex_mpv_shim/gdm.py -> /home/user/Downloads/plex-mpv-shim/pkg/plex-mpv-shim/usr/lib/python3.12/site-packages/plex_mpv_shim
copying build/lib/plex_mpv_shim/gui_mgr.py -> /home/user/Downloads/plex-mpv-shim/pkg/plex-mpv-shim/usr/lib/python3.12/site-packages/plex_mpv_shim
copying build/lib/plex_mpv_shim/media.py -> /home/user/Downloads/plex-mpv-shim/pkg/plex-mpv-shim/usr/lib/python3.12/site-packages/plex_mpv_shim
copying build/lib/plex_mpv_shim/menu.py -> /home/user/Downloads/plex-mpv-shim/pkg/plex-mpv-shim/usr/lib/python3.12/site-packages/plex_mpv_shim
copying build/lib/plex_mpv_shim/mpv_shim.py -> /home/user/Downloads/plex-mpv-shim/pkg/plex-mpv-shim/usr/lib/python3.12/site-packages/plex_mpv_shim
copying build/lib/plex_mpv_shim/player.py -> /home/user/Downloads/plex-mpv-shim/pkg/plex-mpv-shim/usr/lib/python3.12/site-packages/plex_mpv_shim
copying build/lib/plex_mpv_shim/subscribers.py -> /home/user/Downloads/plex-mpv-shim/pkg/plex-mpv-shim/usr/lib/python3.12/site-packages/plex_mpv_shim
copying build/lib/plex_mpv_shim/svp_integration.py -> /home/user/Downloads/plex-mpv-shim/pkg/plex-mpv-shim/usr/lib/python3.12/site-packages/plex_mpv_shim
copying build/lib/plex_mpv_shim/timeline.py -> /home/user/Downloads/plex-mpv-shim/pkg/plex-mpv-shim/usr/lib/python3.12/site-packages/plex_mpv_shim
copying build/lib/plex_mpv_shim/utils.py -> /home/user/Downloads/plex-mpv-shim/pkg/plex-mpv-shim/usr/lib/python3.12/site-packages/plex_mpv_shim
copying build/lib/plex_mpv_shim/video_profile.py -> /home/user/Downloads/plex-mpv-shim/pkg/plex-mpv-shim/usr/lib/python3.12/site-packages/plex_mpv_shim
copying build/lib/plex_mpv_shim/win_utils.py -> /home/user/Downloads/plex-mpv-shim/pkg/plex-mpv-shim/usr/lib/python3.12/site-packages/plex_mpv_shim
copying build/lib/plex_mpv_shim/mouse.lua -> /home/user/Downloads/plex-mpv-shim/pkg/plex-mpv-shim/usr/lib/python3.12/site-packages/plex_mpv_shim
copying build/lib/plex_mpv_shim/systray.png -> /home/user/Downloads/plex-mpv-shim/pkg/plex-mpv-shim/usr/lib/python3.12/site-packages/plex_mpv_shim
byte-compiling /home/user/Downloads/plex-mpv-shim/pkg/plex-mpv-shim/usr/lib/python3.12/site-packages/plex_mpv_shim/__init__.py to __init__.cpython-312.pyc
byte-compiling /home/user/Downloads/plex-mpv-shim/pkg/plex-mpv-shim/usr/lib/python3.12/site-packages/plex_mpv_shim/action_thread.py to action_thread.cpython-312.pyc
byte-compiling /home/user/Downloads/plex-mpv-shim/pkg/plex-mpv-shim/usr/lib/python3.12/site-packages/plex_mpv_shim/bulk_subtitle.py to bulk_subtitle.cpython-312.pyc
byte-compiling /home/user/Downloads/plex-mpv-shim/pkg/plex-mpv-shim/usr/lib/python3.12/site-packages/plex_mpv_shim/cli_mgr.py to cli_mgr.cpython-312.pyc
byte-compiling /home/user/Downloads/plex-mpv-shim/pkg/plex-mpv-shim/usr/lib/python3.12/site-packages/plex_mpv_shim/client.py to client.cpython-312.pyc
byte-compiling /home/user/Downloads/plex-mpv-shim/pkg/plex-mpv-shim/usr/lib/python3.12/site-packages/plex_mpv_shim/conf.py to conf.cpython-312.pyc
byte-compiling /home/user/Downloads/plex-mpv-shim/pkg/plex-mpv-shim/usr/lib/python3.12/site-packages/plex_mpv_shim/conffile.py to conffile.cpython-312.pyc
byte-compiling /home/user/Downloads/plex-mpv-shim/pkg/plex-mpv-shim/usr/lib/python3.12/site-packages/plex_mpv_shim/gdm.py to gdm.cpython-312.pyc
byte-compiling /home/user/Downloads/plex-mpv-shim/pkg/plex-mpv-shim/usr/lib/python3.12/site-packages/plex_mpv_shim/gui_mgr.py to gui_mgr.cpython-312.pyc
byte-compiling /home/user/Downloads/plex-mpv-shim/pkg/plex-mpv-shim/usr/lib/python3.12/site-packages/plex_mpv_shim/media.py to media.cpython-312.pyc
byte-compiling /home/user/Downloads/plex-mpv-shim/pkg/plex-mpv-shim/usr/lib/python3.12/site-packages/plex_mpv_shim/menu.py to menu.cpython-312.pyc
byte-compiling /home/user/Downloads/plex-mpv-shim/pkg/plex-mpv-shim/usr/lib/python3.12/site-packages/plex_mpv_shim/mpv_shim.py to mpv_shim.cpython-312.pyc
byte-compiling /home/user/Downloads/plex-mpv-shim/pkg/plex-mpv-shim/usr/lib/python3.12/site-packages/plex_mpv_shim/player.py to player.cpython-312.pyc
byte-compiling /home/user/Downloads/plex-mpv-shim/pkg/plex-mpv-shim/usr/lib/python3.12/site-packages/plex_mpv_shim/subscribers.py to subscribers.cpython-312.pyc
byte-compiling /home/user/Downloads/plex-mpv-shim/pkg/plex-mpv-shim/usr/lib/python3.12/site-packages/plex_mpv_shim/svp_integration.py to svp_integration.cpython-312.pyc
byte-compiling /home/user/Downloads/plex-mpv-shim/pkg/plex-mpv-shim/usr/lib/python3.12/site-packages/plex_mpv_shim/timeline.py to timeline.cpython-312.pyc
byte-compiling /home/user/Downloads/plex-mpv-shim/pkg/plex-mpv-shim/usr/lib/python3.12/site-packages/plex_mpv_shim/utils.py to utils.cpython-312.pyc
byte-compiling /home/user/Downloads/plex-mpv-shim/pkg/plex-mpv-shim/usr/lib/python3.12/site-packages/plex_mpv_shim/video_profile.py to video_profile.cpython-312.pyc
byte-compiling /home/user/Downloads/plex-mpv-shim/pkg/plex-mpv-shim/usr/lib/python3.12/site-packages/plex_mpv_shim/win_utils.py to win_utils.cpython-312.pyc
writing byte-compilation script '/tmp/tmpqy0b1lp5.py'
/usr/bin/python /tmp/tmpqy0b1lp5.py
removing /tmp/tmpqy0b1lp5.py
running install_egg_info
running egg_info
writing plex_mpv_shim.egg-info/PKG-INFO
writing dependency_links to plex_mpv_shim.egg-info/dependency_links.txt
writing entry points to plex_mpv_shim.egg-info/entry_points.txt
writing requirements to plex_mpv_shim.egg-info/requires.txt
writing top-level names to plex_mpv_shim.egg-info/top_level.txt
reading manifest file 'plex_mpv_shim.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no files found matching '*' under directory 'plex_mpv_shim/default_shader_pack'
adding license file 'LICENSE.md'
writing manifest file 'plex_mpv_shim.egg-info/SOURCES.txt'
Copying plex_mpv_shim.egg-info to /home/user/Downloads/plex-mpv-shim/pkg/plex-mpv-shim/usr/lib/python3.12/site-packages/plex_mpv_shim-1.11.0-py3.12.egg-info
running install_scripts
Installing plex-mpv-shim script to /home/user/Downloads/plex-mpv-shim/pkg/plex-mpv-shim/usr/bin
==> Tidying install...
  -> Removing libtool files...
  -> Purging unwanted files...
  -> Removing static library files...
  -> Stripping unneeded symbols from binaries and libraries...
  -> Compressing man and info pages...
==> Checking for packaging issues...
==> Creating package "plex-mpv-shim"...
  -> Generating .PKGINFO file...
  -> Generating .BUILDINFO file...
  -> Generating .MTREE file...
  -> Compressing package...
==> Leaving fakeroot environment.
==> Finished making: plex-mpv-shim 1.11.0-1 (Wed 15 May 2024 03:54:46 PM EDT)
==> Installing package plex-mpv-shim with pacman -U...
loading packages...
warning: plex-mpv-shim-1.11.0-1 is up to date -- reinstalling
resolving dependencies...
looking for conflicting packages...

Packages (1) plex-mpv-shim-1.11.0-1

Total Installed Size:  0.58 MiB
Net Upgrade Size:      0.00 MiB

:: Proceed with installation? [Y/n] y 
(1/1) checking keys in keyring                                     [------------------------------------] 100%
(1/1) checking package integrity                                   [------------------------------------] 100%
(1/1) loading package files                                        [------------------------------------] 100%
(1/1) checking for file conflicts                                  [------------------------------------] 100%
(1/1) checking available disk space                                [------------------------------------] 100%
warning: could not get file information for usr/bin/plex-mpv-shim
:: Running pre-transaction hooks...
(1/1) Creating Timeshift snapshot before upgrade...
Using system disk as snapshot device for creating snapshots in BTRFS mode
Mounted '/dev/nvme0n1p2' at '/run/timeshift/3330036/backup'
btrfs: Quotas are not enabled
Creating new backup...(BTRFS)
Saving to device: /dev/nvme0n1p2, mounted at path: /run/timeshift/3330036/backup
Created directory: /run/timeshift/3330036/backup/timeshift-btrfs/snapshots/2024-05-15_15-55-00
Created subvolume snapshot: /run/timeshift/3330036/backup/timeshift-btrfs/snapshots/2024-05-15_15-55-00/@
Created subvolume snapshot: /run/timeshift/3330036/backup/timeshift-btrfs/snapshots/2024-05-15_15-55-00/@home
Created control file: /run/timeshift/3330036/backup/timeshift-btrfs/snapshots/2024-05-15_15-55-00/info.json
BTRFS Snapshot saved successfully (0s)
Tagged snapshot '2024-05-15_15-55-00': ondemand
------------------------------------------------------------------------------
Mounted '/dev/nvme0n1p2' at '/run/timeshift/3330187/backup'
btrfs: Quotas are not enabled
------------------------------------------------------------------------------
Removing snapshot: 2024-05-14_16-20-34
Deleting subvolume: @home (Id:6117)
Deleted subvolume: @home (Id:6117)

Deleting subvolume: @ (Id:6116)
Deleted subvolume: @ (Id:6116)

Deleted directory: /run/timeshift/3330187/backup/timeshift-btrfs/snapshots/2024-05-14_16-20-34
Removed snapshot: 2024-05-14_16-20-34
------------------------------------------------------------------------------
:: Processing package changes...
(1/1) reinstalling plex-mpv-shim                                   [------------------------------------] 100%
:: Running post-transaction hooks...
(1/5) Arming ConditionNeedsUpdate...
(2/5) Foreign/AUR package notification
86box 4.0-1
abcde 2.9.3-5
ananicy-cpp 1.1.1-1
apg 2.2.3-5
appimagelauncher 2.2.0-6.4
aseprite 1.3.2-3
balena-etcher 2:1.18.12-1.1
brother-hl-l3290cdw 1.0.2-0
btrfs-assistant 1.8-2
btrfsmaintenance 0.5-2
cachyos-ananicy-rules-git 20240229.r305.gead94ba-1
camlidl 1.12-2
camlidl-debug 1.12-2
candy-icons-git r1062.1c5b81a-1
cd-discid 1.4-3
chaotic-keyring 20230616-1
chaotic-mirrorlist 20230823-1
ckb-next 0.6.0-1
ckbcomp 1.221-1
clang15 15.0.7-2
cncnet 1.0-1
compiler-rt15 15.0.7-1
cura-bin 5.4.0-1
discord-game-sdk 3.2.1-1
dosbox-ece-exodos 4253-5.1
dosbox-ece-r4301 4301-5.1
dosbox-ece-r4358 4358-5.1
dosbox-staging 1:0.81.0-2
dosbox-staging-debug 1:0.81.0-2
downgrade 11.3.0-1
eduke32 20230811.r10345_21bae1455-1
electron19-bin 19.1.9-1
electron25 25.9.8-5
feishin-appimage 0.3.0-1
find-the-command-git 2.0.1.r0.gfecba1a-1.1
fish-autopair 1.0.4-1
flashplayer-standalone 32.0.0.465-1
game-devices-udev 0.22-0.2
garuda-settings-manager-git 1.0.2.r6.ga7ef248-1
garuda-settings-manager-kcm-git 1.0.2.r6.ga7ef248-1
gcdemu 3.2.6-1.3
goverlay-git 0.9.1.r6.g9f80288-1
gtkpod 2.1.5-7
gzdoom-git 4.11pre+349+g17ab6e851-1
heroic-games-launcher-bin 2.9.1-2
higan 110-2
hollywood 1.21-7
httpfs2-2gbplus 0.1.5-1
httpfs2-2gbplus-debug 0.1.5-1
iir1 1.9.4-1
intel-ipsec-mb 1.4-1
ipscan 3.9.1-2
java-openjdk-ea-bin 22b13-1
jdk-temurin 20.0.2.u9-1
kde-servicemenus-rootactions 2.9.1-2.3
khotkeys 5.27.10-1
khtml 5.115.0-1
kjs 5.115.0-1
kpeoplevcard 0.1-2
kquickcharts5 5.115.0-1
krunner5 5.115.0-1
kwin-effects-sliding-notifications 1.5.0-1
kwin-scripts-forceblur 0.6.1-1.3
lact 0.5.0-1
libanjuta 3.34.0-9
libcurl-openssl-1.0 7.79.1-1
libinput-gestures 2.74-1
libinput_gestures_qt 0.3.2+7+g0868859-1.3
libmt32emu 2.4.2-5.1
lightly-qt 0.4.1-1
linux-wifi-hotspot 4.5.0-1
llvm15-libs 15.0.7-1
lockdown-ms 20130326-4
losslesscut-bin 3.56.0-1
makemkv 1.17.6-1
makemkv-debug 1.17.6-1
mission-center 0.3.1-1
mkinitcpio-openswap 0.1.0-3.1
mpv-git-debug 0.37.0_793_g32817198bb-1
munt 2.7.0-4
noto-color-emoji-fontconfig 1.0.0-1
ocamlfuse 2.7.1-13
ocamlfuse-debug 2.7.1-13
ocrmypdf 14.4.0-2
openssl-1.0 1.0.2.u-6
os-prober-btrfs 1.79-5
pace 1.4.2-1.3
paleofetch-garuda r3.6471340-1
paru 1.11.1-1.3
perl-gtk2-ex-form-factory 0.67-1
perl-gtk2-ex-simple-list 0.50-2
perl-mojolicious 9.33-1
perl-musicbrainz-discid 0.06-2
phoronix-test-suite 10.8.4-1.1
plasma5-applets-eventcalendar 76-1.3
plasma5-applets-window-appmenu 0.8.0-1.3
plasma5-applets-window-title 0.7.1-2.3
plasma5-wallpapers-wallpaper-engine 0.5.4-5
plex-media-player 2.58.1-3.6
plex-mpv-shim 1.11.0-1
plymouth-git 22.02.122.r192.g4a6fcf0b-1
preload 0.6.4-9
protontricks 1.10.3-1
pyside2 5.15.13-1
python-eyed3 1:0.9.6-1
python-mpv-jsonipc 1.2.0-2
python-shiboken2 5.15.13-1
python-vdf 3.4-2
python2 2.7.18-8
python2-setuptools 2:44.1.1-2
qdirstat 1.8.1-1.3
qgpgme-qt5 1.23.2-1
rankmirrors r2.60f7568-1
rate-mirrors 0.16.4-1
readline7 7.0.005-1
reflector-simple 3.3-1
replay-sorcery 0.6.0-1
resvg 0.35.0-1
rustdesk-bin 1.2.2-3
snapper-tools 1.1.3-1
soundkonverter 3.0.1-8
speedometer-git 2.8.r36.g43b25e8-1
steamtinkerlaunch 12.12-1.2
stress-ng 0.17.06-1
stress-ng-debug 0.17.06-1
sweet-gtk-theme-dark 3.0-1
systemd-guest-user 33.2-1.1
systemd-oomd-defaults 253.5-1
teamviewer 15.45.3-1
timeshift-autosnap 0.9-1.3
update-grub 0.0.1-8
ventoy-bin 1.0.95-1
vi-vim-symlink 1-2
vkbasalt 0.3.2.10-1
warp-terminal-debug 0.2024.02.20.08.01.stable_01-1
whoogle-git _r749.g92e8ede-1
wine-mono-bin 6.1.1-2
winetricks-git 20230212.r50.g9899670f-1
xcursor-sweet 20200612-1
yay 12.1.2-1
youtube-dl 2021.12.17-2
youtube-dlp 2021.09.25-1
zmusic 1.1.12-1
zoom 5.15.11-1
(3/5) Orphaned package notification...
asciidoc 10.2.0-6
blueprint-compiler 0.12.0-2
bluez-qt5 5.115.0-1
boost 1.83.0-7
clang15 15.0.7-2
cmake 3.29.3-1
devhelp 43.0-1
dotnet-runtime-7.0 7.0.18.sdk118-1
dpkg 1.22.6-1
eigen 3.4.0-2
electron25 25.9.8-5
electron28 28.3.1-2
elfutils 0.191-3
frameworkintegration5 5.115.0-1
gcab 1.6-1
gjs 2:1.80.2-2
gn 0.2165.f284b6b4-1
grantlee 5.3.1-1
gtkmm 1:2.24.5-4
itstool 1:2.0.7-2
just 1.25.2-1
kactivities-stats5 5.115.0-1
kcalendarcore5 5.115.0-1
kdesu5 5.115.0-1
kdsoap-qt5 2.2.0-1
kholidays5 1:5.115.0-1
khtml 5.115.0-1
kidletime5 5.115.0-1
kimageannotator-qt5 0.7.1-3
kirigami-addons5 0.11.0-7
kpeoplevcard 0.1-2
kquickcharts5 5.115.0-1
krunner5 5.115.0-1
ldns 1.8.3-2
libliftoff 0.4.1-1
libqaccessibilityclient-qt5 0.6.0-1
libsmbios 2.4.3-7
libxres 1.2.2-1
meson 1.4.0-5
modemmanager-qt5 5.115.0-1
networkmanager-qt5 5.115.0-1
oxygen-sounds 6.0.4-1
perl-ipc-run3 0.049-1
plasma-wayland-protocols 1.12.0-1
pyside2 5.15.13-1
python-build 1.2.1-3
python-docutils 1:0.21.2-1
python-google-api-python-client 2.123.0-2
python-google-auth-oauthlib 1.2.0-3
python-importlib-metadata 5.1.0-2
python-installer 0.7.0-8
python-ply 3.11-13
python-pycurl 7.45.2-4
python-pydantic 2.7.1-2
python-routes 2.5.1-7
qgpgme-qt5 1.23.2-1
qqc2-desktop-style5 5.115.0-1
qtkeychain-qt5 0.14.3-1
rclone 1.66.0-1
seatd 0.8.0-1
suil 0.10.20-1
taglib1 1.13.1-2
tomlplusplus 3.4.0-1
vala 0.56.17-1
wayland-protocols 1.36-1
webkit2gtk 2.44.1-1
webrtc-audio-processing 0.3.1-4
xcb-util-errors 1.0.1-1
(4/5) Checking for .pacnew and .pacsave files...
.pac* files found:
/etc/cups/cupsd.conf.pacnew
/etc/nsswitch.conf.pacnew
/etc/passwd.pacnew
/etc/shells.pacnew
/etc/locale.gen.pacnew
/etc/default/grub.pacnew
/etc/default/grub-btrfs/config.pacnew
/etc/pam.d/kde.pacnew
/etc/libreoffice/sofficerc.pacsave
/etc/libvirt/qemu.conf.pacnew
/etc/mkinitcpio.conf.pacnew
/etc/ssh/ssh_config.pacnew
/etc/ssh/sshd_config.pacnew
/etc/pacman.conf.pacnew
/etc/pacman.d/mirrorlist.pacnew
/etc/plymouth/plymouthd.conf.pacnew
/etc/sudoers.pacnew
/etc/systemd/system.conf.pacnew
/etc/systemd/user.conf.pacnew
Please check and merge
(5/5) Syncing all file systems...
==> Cleaning up...
❯ plex-mpv-shim
2024-05-15 15:55:04,352 [   ERROR] conf: Error loading settings from json: Expecting value: line 41 column 21 (char 1089)
2024-05-15 15:55:04,352 [ WARNING] root: Cannot load GUI. Falling back to command line interface.
Traceback (most recent call last):
  File "/usr/lib/python3.12/site-packages/plex_mpv_shim/mpv_shim.py", line 39, in main
    from .gui_mgr import userInterface
  File "/usr/lib/python3.12/site-packages/plex_mpv_shim/gui_mgr.py", line 1, in <module>
    from pystray import Icon, MenuItem, Menu
ModuleNotFoundError: No module named 'pystray'
2024-05-15 15:55:04,395 [ WARNING] player: Could not find libmpv1.
Traceback (most recent call last):
  File "/usr/bin/plex-mpv-shim", line 33, in <module>
    sys.exit(load_entry_point('plex-mpv-shim==1.11.0', 'console_scripts', 'plex-mpv-shim')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/plex_mpv_shim/mpv_shim.py", line 47, in main
    from .player import playerManager
  File "/usr/lib/python3.12/site-packages/plex_mpv_shim/player.py", line 31, in <module>
    import python_mpv_jsonipc as mpv
ModuleNotFoundError: No module named 'python_mpv_jsonipc'

**Comment by polyzen** [comment]
Maybe try rebuilding and reinstalling aur/python-mpv-jsonipc

**Comment by polyzen** [comment]
Alright then it seems this can be closed in favor of #109
